[project]
name = "pdf-outliner"
version = "0.1.0"
description = "Add outlines to PDF files based on recipe files"
requires-python = ">=3.8"
dependencies = ["pypdf>=5.1.0"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
